%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.4 and Fixed-Point Designer 6.1           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function e = nlms_wrapper_fixpt(d,u,Pest,A_st,N)
    fm = get_fimath();
    d_in = fi( d, 1, 3, 0, fm );
    u_in = fi( u, 1, 3, 0, fm );
    Pest_in = fi( Pest, 0, 16, 9, fm );
    A_st_in = fi( A_st, 1, 16, 20, fm );
    N_in = fi( N, 0, 8, 0, fm );
    [e_out] = nlms_fixpt( d_in, u_in, Pest_in, A_st_in, N_in );
    e = double( e_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
